// Code generated by MockGen. DO NOT EDIT.
// Source: internal/accrual-system/inteface.go
//
// Generated by this command:
//
//	mockgen -source=internal/accrual-system/inteface.go -destination=mock/system_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccrualService is a mock of AccrualService interface.
type MockAccrualService struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualServiceMockRecorder
	isgomock struct{}
}

// MockAccrualServiceMockRecorder is the mock recorder for MockAccrualService.
type MockAccrualServiceMockRecorder struct {
	mock *MockAccrualService
}

// NewMockAccrualService creates a new mock instance.
func NewMockAccrualService(ctrl *gomock.Controller) *MockAccrualService {
	mock := &MockAccrualService{ctrl: ctrl}
	mock.recorder = &MockAccrualServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualService) EXPECT() *MockAccrualServiceMockRecorder {
	return m.recorder
}

// OrderProcess mocks base method.
func (m *MockAccrualService) OrderProcess(orderID int) *http.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderProcess", orderID)
	ret0, _ := ret[0].(*http.Response)
	return ret0
}

// OrderProcess indicates an expected call of OrderProcess.
func (mr *MockAccrualServiceMockRecorder) OrderProcess(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderProcess", reflect.TypeOf((*MockAccrualService)(nil).OrderProcess), orderID)
}
